[package]
name = "single-link-list"
version = "0.1.0"
authors = ["ttang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
